// Auto-generated by crawler (npm run export:local). Do not edit by hand.
window.WAI_PARKING_DATA = {
  "__generatedAt": "2026-09-28T23:12:13.607Z",
  "taitungCounty": [
    {
      "name": "停車場",
      "lat": 22.9767793,
      "lng": 121.3048862,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9772856,
      "lng": 121.3079855,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6881141,
      "lng": 121.0168383,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7908948,
      "lng": 121.1916604,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9053015,
      "lng": 121.0908382,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8721225,
      "lng": 121.2258594,
      "notes": "免費",
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8873145,
      "lng": 121.2107543,
      "notes": "免費",
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8115441,
      "lng": 121.1501738,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8124463,
      "lng": 121.1420048,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7537194,
      "lng": 121.1479567,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7911106,
      "lng": 121.1404976,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.2641983,
      "lng": 120.9616509,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7343045,
      "lng": 121.0655547,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7373051,
      "lng": 121.0682472,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7382124,
      "lng": 121.0677359,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7375876,
      "lng": 121.0664868,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.739002,
      "lng": 121.0658693,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7398047,
      "lng": 121.0669269,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7361283,
      "lng": 121.0692553,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7375082,
      "lng": 121.0695419,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7503675,
      "lng": 121.1446217,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7494019,
      "lng": 121.1416671,
      "source": "osm"
    },
    {
      "name": "太平溪停車場",
      "lat": 22.7500194,
      "lng": 121.1402193,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7503901,
      "lng": 121.1427312,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.2473464,
      "lng": 120.9858724,
      "source": "osm"
    },
    {
      "name": "台東縣立平面停車場",
      "lat": 22.7544354,
      "lng": 121.1463088,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8725378,
      "lng": 121.2254191,
      "notes": "免費",
      "source": "osm"
    },
    {
      "name": "大型車停車場",
      "lat": 22.3366681,
      "lng": 120.8944815,
      "source": "osm"
    },
    {
      "name": "小型車停車場",
      "lat": 22.3373643,
      "lng": 120.8949465,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.1730181,
      "lng": 121.0424944,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7652632,
      "lng": 121.1462839,
      "source": "osm"
    },
    {
      "name": "小型車停車場",
      "lat": 22.6895378,
      "lng": 120.9918685,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8643282,
      "lng": 121.0934666,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.5352901,
      "lng": 120.9622852,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7499991,
      "lng": 121.1472033,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7101421,
      "lng": 121.0598777,
      "source": "osm"
    },
    {
      "name": "臺北榮民總醫院臺東分院停車場",
      "lat": 22.7723974,
      "lng": 121.133296,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.0991694,
      "lng": 121.377519,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7724966,
      "lng": 121.1342574,
      "source": "osm"
    },
    {
      "name": "國立臺東專科學校(附設高職部)停車場",
      "lat": 22.7571769,
      "lng": 121.1242786,
      "source": "osm"
    },
    {
      "name": "國立臺東專科學校(附設高職部)停車場",
      "lat": 22.757396,
      "lng": 121.1237299,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.0242575,
      "lng": 121.5555016,
      "source": "osm"
    },
    {
      "name": "台東富岡街公有停車場",
      "lat": 22.7924051,
      "lng": 121.1900691,
      "notes": "收費",
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7919449,
      "lng": 121.1906398,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7900212,
      "lng": 121.1846977,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7927842,
      "lng": 121.1921378,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6749796,
      "lng": 121.5042796,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9940849,
      "lng": 121.1196112,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7558979,
      "lng": 121.1496641,
      "source": "osm"
    },
    {
      "name": "小客車停車場",
      "lat": 22.0279587,
      "lng": 121.5354735,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7606588,
      "lng": 121.0929649,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7592941,
      "lng": 121.0921349,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.1629308,
      "lng": 121.0518268,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7069401,
      "lng": 121.0528227,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.3813647,
      "lng": 120.9125277,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7646434,
      "lng": 121.1189132,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7955222,
      "lng": 121.1954445,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7635655,
      "lng": 121.1582093,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7693107,
      "lng": 121.1213589,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7681217,
      "lng": 121.1189398,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7037763,
      "lng": 121.0289111,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6960253,
      "lng": 121.0223405,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6925529,
      "lng": 121.020167,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6929771,
      "lng": 121.0175977,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.693166,
      "lng": 121.0140662,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6922451,
      "lng": 121.0064417,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6734833,
      "lng": 121.0402377,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6689278,
      "lng": 121.0349023,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.1202783,
      "lng": 121.2226173,
      "smallSpots": 25,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.1012864,
      "lng": 121.3837089,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.1225705,
      "lng": 121.4073722,
      "notes": "收費",
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8680623,
      "lng": 121.2184989,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7560204,
      "lng": 121.1080486,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.3147121,
      "lng": 121.4518065,
      "notes": "免費",
      "source": "osm"
    },
    {
      "name": "台灣鐵路管理局台東火車站停車場",
      "lat": 22.7949445,
      "lng": 121.1242907,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7947737,
      "lng": 121.1255456,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8071404,
      "lng": 121.1965468,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8614121,
      "lng": 121.2039434,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8637589,
      "lng": 121.2063036,
      "notes": "免費",
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8570149,
      "lng": 121.1984877,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9453934,
      "lng": 121.2798519,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8658796,
      "lng": 121.2145671,
      "notes": "免費",
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9892363,
      "lng": 121.2953142,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.1716873,
      "lng": 121.4018266,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.2150747,
      "lng": 121.408725,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9324876,
      "lng": 121.1554628,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8873161,
      "lng": 121.1667332,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8970366,
      "lng": 121.1614906,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8109715,
      "lng": 121.1086499,
      "source": "osm"
    },
    {
      "name": "麻荖漏步道停車場",
      "lat": 23.1294246,
      "lng": 121.3478469,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.1753432,
      "lng": 121.0299488,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.2519805,
      "lng": 120.8939302,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8724861,
      "lng": 121.1794173,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.0486892,
      "lng": 121.1637932,
      "source": "osm"
    },
    {
      "name": "鹿野火車站停車場",
      "lat": 22.912581,
      "lng": 121.136593,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.3678464,
      "lng": 120.8497306,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8940175,
      "lng": 121.0637065,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8766336,
      "lng": 121.0558831,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.227322,
      "lng": 121.4170114,
      "source": "osm"
    },
    {
      "name": "停車場(僅可停放三部汽車)",
      "lat": 22.8956539,
      "lng": 121.0719733,
      "source": "osm"
    },
    {
      "name": "紅葉野溪溫泉停車場",
      "lat": 22.9018149,
      "lng": 121.0727352,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9035469,
      "lng": 121.0759079,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.2482573,
      "lng": 121.417758,
      "source": "osm"
    },
    {
      "name": "陳大姐名產店停車場",
      "lat": 23.1875171,
      "lng": 121.0237631,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9131511,
      "lng": 121.1192641,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9159992,
      "lng": 121.1221635,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.750288,
      "lng": 121.1581147,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7620694,
      "lng": 121.15866,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7524328,
      "lng": 121.1646426,
      "notes": "免費",
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.753492,
      "lng": 121.1646,
      "notes": "免費",
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7520738,
      "lng": 121.1630267,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7496398,
      "lng": 121.157499,
      "notes": "免費",
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6714956,
      "lng": 121.4944001,
      "source": "osm"
    },
    {
      "name": "垃圾車車庫",
      "lat": 22.6687481,
      "lng": 121.4691246,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6678366,
      "lng": 121.4688389,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6366305,
      "lng": 121.5036181,
      "notes": "免費",
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.0918593,
      "lng": 121.2403945,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.126134,
      "lng": 121.2199756,
      "notes": "免費",
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.1117785,
      "lng": 121.2262122,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.3942336,
      "lng": 121.475178,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.3943517,
      "lng": 121.4757877,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9736327,
      "lng": 121.3109726,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.018725,
      "lng": 121.3240874,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9150757,
      "lng": 121.1215264,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9178248,
      "lng": 121.1224585,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8657003,
      "lng": 121.1083997,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.866278,
      "lng": 121.1088829,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6747796,
      "lng": 121.4925209,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6719456,
      "lng": 121.4674733,
      "source": "osm"
    },
    {
      "name": "停車棚",
      "lat": 22.6727551,
      "lng": 121.467849,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6722242,
      "lng": 121.4686767,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6620355,
      "lng": 121.4728509,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6715828,
      "lng": 121.5063478,
      "source": "osm"
    },
    {
      "name": "員工停車場",
      "lat": 23.0576576,
      "lng": 121.1660139,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7576643,
      "lng": 121.1499902,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.171686,
      "lng": 121.400505,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.5313133,
      "lng": 120.9668511,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6186619,
      "lng": 121.0051284,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.5904547,
      "lng": 120.9327438,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.5951394,
      "lng": 120.9401993,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.6125496,
      "lng": 121.0067307,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7644714,
      "lng": 121.1466628,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7671136,
      "lng": 121.1436722,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.792421,
      "lng": 121.126874,
      "source": "osm"
    },
    {
      "name": "池上遊客服務中心停車場",
      "lat": 23.1345118,
      "lng": 121.2332899,
      "smallSpots": 13,
      "notes": "免費",
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.0836754,
      "lng": 121.1638961,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.0837223,
      "lng": 121.1648507,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.0846605,
      "lng": 121.1632208,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.5965652,
      "lng": 120.9942609,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.2627906,
      "lng": 121.3874781,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.2618443,
      "lng": 121.387157,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9239518,
      "lng": 121.1248886,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8011222,
      "lng": 121.0948327,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8011179,
      "lng": 121.094177,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8285608,
      "lng": 121.1519077,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.1744712,
      "lng": 121.400918,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.1239446,
      "lng": 121.2203942,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8814314,
      "lng": 121.231985,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.9578052,
      "lng": 121.2954433,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7981283,
      "lng": 121.07112,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.2939061,
      "lng": 120.8828929,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.2801449,
      "lng": 120.8898881,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.3655565,
      "lng": 120.9013743,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8948919,
      "lng": 121.1173393,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8980552,
      "lng": 121.1005564,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.762655,
      "lng": 121.1573753,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8384571,
      "lng": 121.1874523,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7768234,
      "lng": 121.0588902,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.8032081,
      "lng": 121.0601087,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7558699,
      "lng": 121.1459576,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 23.0985087,
      "lng": 121.1760416,
      "source": "osm"
    },
    {
      "name": "停車場",
      "lat": 22.7915726,
      "lng": 121.1240819,
      "notes": "收費",
      "source": "osm"
    },
    {
      "name": "中央市場停車場",
      "lat": 22.7528341,
      "lng": 121.1491719,
      "address": "台東市信義路187-179號",
      "phone": "089-342500",
      "smallSpots": 28,
      "motoSpots": 45,
      "source": "taitung_gov_parking"
    },
    {
      "name": "停五公有停車場",
      "lat": 22.7552484,
      "lng": 121.1448522,
      "address": "台東市新生路191號",
      "phone": "089-225228",
      "smallSpots": 73,
      "source": "taitung_gov_parking"
    },
    {
      "name": "光明路停車場(月租)",
      "lat": 22.7527036,
      "lng": 121.1491123,
      "address": "台東市光明路264號",
      "phone": "0929-129888",
      "smallSpots": 9,
      "source": "taitung_gov_parking"
    },
    {
      "name": "加路蘭遊憩區停車場",
      "lat": 22.8063665,
      "lng": 121.1969974,
      "address": "台東市台11線",
      "phone": "089-280313",
      "largeSpots": 4,
      "smallSpots": 28,
      "motoSpots": 20,
      "source": "taitung_gov_parking"
    },
    {
      "name": "叭叭房台東開封停車場(供宿客)",
      "lat": 22.7594531,
      "lng": 121.1381503,
      "address": "台東市開封街696號",
      "phone": "02-2528-2826",
      "smallSpots": 11,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東停一停車場",
      "lat": 22.7920847,
      "lng": 121.1227377,
      "address": "台東市岩灣路101巷610號後方",
      "phone": "089-226506",
      "smallSpots": 285,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東停二停車場",
      "lat": 22.7945812,
      "lng": 121.1232102,
      "address": "台東市岩灣路101巷439號右方",
      "phone": "089-226506",
      "smallSpots": 203,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東市新生地下停車場",
      "lat": 22.7521461,
      "lng": 121.1475914,
      "address": "台東市新生路93-97號",
      "phone": "089-357718",
      "evSpots": 1,
      "smallSpots": 332,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東森林公園第一停車場",
      "lat": 22.7634187,
      "lng": 121.1588754,
      "address": "台東市華泰路300號",
      "phone": "089-362025",
      "smallSpots": 105,
      "motoSpots": 74,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東火車站四處路外停車場(A區)",
      "lat": 22.7937365,
      "lng": 121.1230986,
      "address": "台東火車站周邊區域",
      "phone": "089-342500",
      "smallSpots": 112,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東火車站四處路外停車場(B區)",
      "lat": 22.7937365,
      "lng": 121.1230986,
      "address": "台東火車站周邊區域",
      "phone": "089-342500",
      "evSpots": 1,
      "smallSpots": 120,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東火車站四處路外停車場(C區)",
      "lat": 22.7937365,
      "lng": 121.1230986,
      "address": "台東火車站周邊區域",
      "phone": "089-342500",
      "motoSpots": 630,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東火車站四處路外停車場(D區)",
      "lat": 22.7937365,
      "lng": 121.1230986,
      "address": "台東火車站周邊區域",
      "phone": "089-342500",
      "smallSpots": 89,
      "source": "taitung_gov_parking"
    },
    {
      "name": "台東航空站停車場",
      "lat": 22.761315,
      "lng": 121.1439117,
      "address": "台東市民航路1100號",
      "phone": "089-361111",
      "evSpots": 4,
      "smallSpots": 209,
      "source": "taitung_gov_parking"
    },
    {
      "name": "國立臺東大學產學創新園區停車場",
      "lat": 22.7505589,
      "lng": 121.1472319,
      "address": "台東市中華路一段684號",
      "phone": "089-352305",
      "largeSpots": 6,
      "smallSpots": 83,
      "source": "taitung_gov_parking"
    },
    {
      "name": "城市商旅台東鄭州停車場(供宿客)",
      "lat": 22.7618543,
      "lng": 121.1445746,
      "address": "台東市鄭州街13號",
      "phone": "080 020 8333",
      "smallSpots": 86,
      "source": "taitung_gov_parking"
    },
    {
      "name": "基督教醫院停車場",
      "lat": 22.7637889,
      "lng": 121.1461593,
      "address": "台東市開封街350號",
      "phone": "089-323362",
      "smallSpots": 107,
      "source": "taitung_gov_parking"
    },
    {
      "name": "大同路停車場",
      "lat": 22.7534986,
      "lng": 121.1531208,
      "address": "台東市大同路停車場福建路路口",
      "phone": "089-351999",
      "smallSpots": 33,
      "source": "taitung_gov_parking"
    },
    {
      "name": "富岡地質公園停車場",
      "lat": 22.7943653,
      "lng": 121.1954612,
      "address": "台東市松江路一段500號",
      "phone": "089-281530",
      "largeSpots": 27,
      "smallSpots": 93,
      "motoSpots": 49,
      "source": "taitung_gov_parking"
    },
    {
      "name": "富綠汽車停車場(供遊客)",
      "lat": 22.7929705,
      "lng": 121.1894423,
      "address": "台東市富岡街175號",
      "phone": "0920-054862",
      "smallSpots": 8,
      "source": "taitung_gov_parking"
    },
    {
      "name": "成功鎮三民里第二市場停車場(月租)",
      "lat": 23.1041567,
      "lng": 121.3746756,
      "address": "台東縣成功鎮三民里三民路111號",
      "phone": "089-851004",
      "smallSpots": 8,
      "source": "taitung_gov_parking"
    },
    {
      "name": "旗魚飯店停車場(供宿客)",
      "lat": 22.7506328,
      "lng": 121.1503437,
      "address": "台東市新生路49號",
      "phone": "089-336360",
      "smallSpots": 31,
      "source": "taitung_gov_parking"
    },
    {
      "name": "東大同停車場",
      "lat": 22.75453,
      "lng": 121.1528793,
      "address": "台東市中華路一段376巷7號",
      "phone": "089-321313",
      "smallSpots": 20,
      "source": "taitung_gov_parking"
    },
    {
      "name": "波浪屋停車場",
      "lat": 22.7534225,
      "lng": 121.1472995,
      "address": "台東市新生路170號",
      "phone": "089-342500",
      "smallSpots": 29,
      "source": "taitung_gov_parking"
    },
    {
      "name": "知本國家森林遊樂區停車場",
      "lat": 22.686961,
      "lng": 120.99214,
      "address": "台東縣卑南鄉龍泉路290號",
      "phone": "089-510961#10",
      "smallSpots": 75,
      "source": "taitung_gov_parking"
    },
    {
      "name": "衛生福利部台東醫院停車場",
      "lat": 22.7574517,
      "lng": 121.1508134,
      "address": "台東市五權街1號",
      "phone": "089-324112",
      "smallSpots": 23,
      "source": "taitung_gov_parking"
    },
    {
      "name": "豐榮路停車場(月租型)",
      "lat": 22.7477286,
      "lng": 121.1356096,
      "address": "台東市豐 榮路145巷",
      "phone": "089-351999",
      "smallSpots": 46,
      "source": "taitung_gov_parking"
    },
    {
      "name": "長濱鄉一號停車場(月租)",
      "lat": 23.3180619,
      "lng": 121.4484747,
      "address": "臺東縣長濱鄉長濱村7鄰中興23號",
      "phone": "089-832139",
      "smallSpots": 59,
      "source": "taitung_gov_parking"
    },
    {
      "name": "阿華停車場(供遊客)",
      "lat": 22.7970484,
      "lng": 121.1874228,
      "address": "台東市富岡里松江路一段101巷139之1號",
      "phone": "0905-100530",
      "smallSpots": 16,
      "source": "taitung_gov_parking"
    },
    {
      "name": "馬偕醫院停車場",
      "lat": 22.7511505,
      "lng": 121.1406099,
      "address": "台東市長沙街303巷1號",
      "phone": "089-310150",
      "smallSpots": 79,
      "source": "taitung_gov_parking"
    }
  ]
};
